"use client";

import { FC, useMemo } from "react";

interface RichQuestionContentProps {
  /** K.C. Nag story narrative wrapping */
  richNarrative?: string;
  /** Rendered HTML with story context and visuals */
  richHtmlContent?: string;
  /** Progressive visual hints for problem-solving */
  visualHints?: string[];
  /** Chapter name for context */
  chapter?: string;
  /** Whether to show narrative inline */
  showNarrative?: boolean;
}

/**
 * RichQuestionContent Component
 * 
 * Displays the rich, pedagogical content generated by the Hybrid Neuro-Symbolic Pipeline:
 * - K.C. Nag narrative that provides context and meaning
 * - HTML diagrams with visual representations
 * - Progressive visual hints for problem-solving
 * 
 * This brings the hybrid scaling plan enhancements to life in the frontend.
 * 
 * @example
 * <RichQuestionContent
 *   richNarrative="Raj went to the market..."
 *   richHtmlContent="<div>Visual diagram here</div>"
 *   visualHints={["Look at the numbers", "Consider place value"]}
 *   chapter="LARGE_NUMBERS"
 * />
 */
export const RichQuestionContent: FC<RichQuestionContentProps> = ({
  richNarrative,
  richHtmlContent,
  visualHints,
  chapter,
  showNarrative = true,
}) => {
  // Check if we have any rich content to display
  const hasRichContent = useMemo(
    () => Boolean(richNarrative || richHtmlContent || (visualHints && visualHints.length > 0)),
    [richNarrative, richHtmlContent, visualHints]
  );

  if (!hasRichContent) {
    return null;
  }

  return (
    <div className="space-y-4 bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 border-l-4 border-indigo-400">
      {/* Narrative Context */}
      {showNarrative && richNarrative && (
        <div className="bg-white rounded-xl p-4 border border-indigo-100">
          <div className="flex items-start gap-3">
            <div className="flex-shrink-0">
              <svg
                className="h-6 w-6 text-indigo-600 mt-1"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
            <div className="flex-1">
              <p className="text-sm font-semibold text-indigo-900 mb-2">
                📖 Context & Story
              </p>
              <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                {richNarrative}
              </p>
            </div>
          </div>
        </div>
      )}

      {/* HTML Diagram/Visual Content */}
      {richHtmlContent && (
        <div className="bg-white rounded-xl p-4 border border-indigo-100 overflow-x-auto">
          <p className="text-sm font-semibold text-indigo-900 mb-3">
            🎨 Visual Representation
          </p>
          <div
            className="text-center space-y-4"
            dangerouslySetInnerHTML={{ __html: richHtmlContent }}
          />
        </div>
      )}

      {/* Progressive Visual Hints */}
      {visualHints && visualHints.length > 0 && (
        <div className="bg-white rounded-xl p-4 border border-indigo-100">
          <p className="text-sm font-semibold text-indigo-900 mb-3">
            💡 Visual Hints
          </p>
          <div className="space-y-2">
            {visualHints.map((hint, index) => (
              <div
                key={index}
                className="flex items-start gap-3 p-2 bg-indigo-50 rounded-lg"
              >
                <span className="flex-shrink-0 inline-flex items-center justify-center h-6 w-6 rounded-full bg-indigo-600 text-white text-xs font-semibold">
                  {index + 1}
                </span>
                <p className="text-sm text-gray-700">{hint}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Pedagogical Badge */}
      {chapter && (
        <div className="flex items-center justify-between pt-2 border-t border-indigo-100">
          <span className="text-xs font-semibold text-indigo-600">
            ✨ K.C. Nag Hybrid Learning
          </span>
          <span className="text-xs text-gray-500">{chapter}</span>
        </div>
      )}
    </div>
  );
};

export default RichQuestionContent;
