"""
LLM Batch Template Generator

Generates question templates using LLM (OpenAI/Anthropic) based on:
- Concept taxonomy from backend/config/content/taxonomy/
- Misconception patterns from backend/config/content/rubrics/
- Blueprint requirements from backend/config/content/blueprints/

Usage:
    python -m tools.llm_template_generator --concept "factors" --count 5
    python -m tools.llm_template_generator --chapter "factors_multiples" --batch
    python -m tools.llm_template_generator --from-taxonomy --dry-run
"""

import os
import json
import asyncio
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional
from enum import Enum

import yaml

logger = logging.getLogger(__name__)

# Config paths
CONFIG_BASE = Path(__file__).parent.parent / "config" / "content"
TAXONOMY_PATH = CONFIG_BASE / "taxonomy"
RUBRICS_PATH = CONFIG_BASE / "rubrics"
BLUEPRINTS_PATH = CONFIG_BASE / "blueprints"
GRAPHS_PATH = CONFIG_BASE / "graphs"


class BloomLevel(str, Enum):
    REMEMBER = "REMEMBER"
    UNDERSTAND = "UNDERSTAND"
    APPLY = "APPLY"
    ANALYZE = "ANALYZE"
    EVALUATE = "EVALUATE"
    CREATE = "CREATE"


@dataclass
class TemplateSpec:
    """Specification for generating a template."""
    concept_id: str
    concept_name: str
    bloom_level: str
    difficulty: int
    misconceptions: List[str] = field(default_factory=list)
    prerequisites: List[str] = field(default_factory=list)
    learning_objectives: List[str] = field(default_factory=list)
    example_questions: List[str] = field(default_factory=list)


@dataclass
class GeneratedTemplate:
    """Template generated by LLM."""
    concept_id: str
    template_code: str
    question_pattern: str
    variable_schema: Dict[str, Any]
    answer_logic: str
    option_patterns: List[str]
    difficulty: int
    bloom_level: str
    estimated_time: int
    misconceptions: List[Dict[str, str]] = field(default_factory=list)
    rationale: str = ""  # LLM's explanation of the template
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class LLMTemplateGenerator:
    """
    Generates question templates using LLM based on curriculum config.
    
    Pipeline: Taxonomy → Spec → LLM Prompt → Generated Template → Review Queue
    """
    
    # LLM prompt templates
    SYSTEM_PROMPT = """You are an expert mathematics curriculum designer for CBSE Class 5 students.
Your task is to create question templates that:
1. Follow Bloom's taxonomy levels precisely
2. Include common misconceptions as distractors
3. Use Jinja2 syntax for variable placeholders: {{ variable_name }}
4. Provide clear, educational feedback for wrong answers

Output JSON only. No explanations outside the JSON structure."""

    TEMPLATE_GENERATION_PROMPT = """Create a question template for the following concept:

**Concept:** {concept_name} ({concept_id})
**Bloom Level:** {bloom_level}
**Difficulty:** {difficulty}/5
**Target Misconceptions:** {misconceptions}
**Prerequisites:** {prerequisites}
**Learning Objectives:** {learning_objectives}

Generate a JSON template with this exact structure:
{{
    "template_code": "unique_code_v1",
    "question_pattern": "Question text with {{ variable }} placeholders",
    "variable_schema": {{
        "type": "object",
        "properties": {{
            "variable_name": {{
                "type": "integer",
                "minimum": 1,
                "maximum": 100,
                "description": "What this variable represents"
            }}
        }}
    }},
    "answer_logic": "Python expression using variables dict, e.g., variables['x'] + variables['y']",
    "option_patterns": [
        "{{ correct_answer }}",
        "{{ distractor_1 }}",
        "{{ distractor_2 }}",
        "{{ distractor_3 }}"
    ],
    "estimated_time": 60,
    "misconceptions": [
        {{
            "option_index": 1,
            "misconception_code": "ARITHMETIC_ERROR",
            "why_wrong": "Why student might choose this",
            "teaching_point": "How to correct this thinking"
        }}
    ],
    "rationale": "Brief explanation of why this template tests the concept effectively"
}}

Requirements:
- First option_pattern is ALWAYS the correct answer
- Include 3 distractors based on common misconceptions
- answer_logic must be valid Python that uses variables['key'] syntax
- variable_schema must allow generating diverse question instances
- estimated_time in seconds (30-180 range)"""

    def __init__(
        self,
        llm_provider: str = "openai",
        model: str = "gpt-4",
        api_key: str = None
    ):
        self.llm_provider = llm_provider
        self.model = model
        self.api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self._load_config()
    
    def _load_config(self):
        """Load taxonomy, rubrics, and blueprints."""
        self.taxonomy = {}
        self.rubrics = {}
        self.blueprints = {}
        self.graphs = {}
        
        # Load taxonomy
        if TAXONOMY_PATH.exists():
            for file in TAXONOMY_PATH.glob("*.yaml"):
                with open(file) as f:
                    data = yaml.safe_load(f)
                    if data:
                        self.taxonomy[file.stem] = data
        
        # Load rubrics (misconceptions)
        if RUBRICS_PATH.exists():
            for file in RUBRICS_PATH.glob("*.yaml"):
                with open(file) as f:
                    data = yaml.safe_load(f)
                    if data:
                        self.rubrics[file.stem] = data
        
        # Load blueprints
        if BLUEPRINTS_PATH.exists():
            for file in BLUEPRINTS_PATH.glob("*.yaml"):
                with open(file) as f:
                    data = yaml.safe_load(f)
                    if data:
                        self.blueprints[file.stem] = data
        
        # Load concept graphs
        if GRAPHS_PATH.exists():
            for file in GRAPHS_PATH.glob("*.yaml"):
                with open(file) as f:
                    data = yaml.safe_load(f)
                    if data:
                        self.graphs[file.stem] = data
        
        logger.info(f"Loaded config: {len(self.taxonomy)} taxonomy, "
                   f"{len(self.rubrics)} rubrics, {len(self.blueprints)} blueprints")
    
    def get_concepts_for_chapter(self, chapter_key: str) -> List[TemplateSpec]:
        """Get all concepts that need templates for a chapter."""
        specs = []
        
        # Look up chapter in taxonomy
        chapter_taxonomy = self.taxonomy.get(chapter_key, {})
        concepts = chapter_taxonomy.get("concepts", [])
        
        # Get misconceptions from rubrics
        chapter_rubrics = self.rubrics.get(chapter_key, {})
        misconception_map = chapter_rubrics.get("misconceptions", {})
        
        # Get prerequisites from graphs
        chapter_graph = self.graphs.get(chapter_key, {})
        prereq_map = {}
        for edge in chapter_graph.get("edges", []):
            target = edge.get("target")
            source = edge.get("source")
            if target and source:
                prereq_map.setdefault(target, []).append(source)
        
        # Build specs for each concept at each Bloom level
        for concept in concepts:
            concept_id = concept.get("id", "")
            concept_name = concept.get("name", "")
            learning_objectives = concept.get("objectives", [])
            
            # Get misconceptions for this concept
            concept_misconceptions = misconception_map.get(concept_id, [])
            
            # Get prerequisites
            prerequisites = prereq_map.get(concept_id, [])
            
            # Generate specs for different Bloom levels and difficulties
            bloom_difficulty_map = {
                "REMEMBER": [1, 2],
                "UNDERSTAND": [2, 3],
                "APPLY": [3, 4],
                "ANALYZE": [4, 5],
            }
            
            for bloom, difficulties in bloom_difficulty_map.items():
                for difficulty in difficulties:
                    specs.append(TemplateSpec(
                        concept_id=concept_id,
                        concept_name=concept_name,
                        bloom_level=bloom,
                        difficulty=difficulty,
                        misconceptions=concept_misconceptions[:3],  # Top 3
                        prerequisites=prerequisites,
                        learning_objectives=learning_objectives,
                    ))
        
        return specs
    
    async def generate_template(self, spec: TemplateSpec) -> GeneratedTemplate:
        """Generate a single template using LLM."""
        prompt = self.TEMPLATE_GENERATION_PROMPT.format(
            concept_id=spec.concept_id,
            concept_name=spec.concept_name,
            bloom_level=spec.bloom_level,
            difficulty=spec.difficulty,
            misconceptions=", ".join(spec.misconceptions) or "common arithmetic errors",
            prerequisites=", ".join(spec.prerequisites) or "none",
            learning_objectives="\n".join(f"- {obj}" for obj in spec.learning_objectives) or "understand the concept"
        )
        
        # Call LLM
        response = await self._call_llm(prompt)
        
        # Parse response
        template_data = self._parse_llm_response(response)
        
        return GeneratedTemplate(
            concept_id=spec.concept_id,
            template_code=template_data.get("template_code", f"{spec.concept_id}_{spec.bloom_level.lower()}_v1"),
            question_pattern=template_data.get("question_pattern", ""),
            variable_schema=template_data.get("variable_schema", {}),
            answer_logic=template_data.get("answer_logic", ""),
            option_patterns=template_data.get("option_patterns", []),
            difficulty=spec.difficulty,
            bloom_level=spec.bloom_level,
            estimated_time=template_data.get("estimated_time", 60),
            misconceptions=template_data.get("misconceptions", []),
            rationale=template_data.get("rationale", "")
        )
    
    async def generate_batch(
        self,
        chapter_key: str,
        max_templates: int = 50,
        dry_run: bool = False
    ) -> List[GeneratedTemplate]:
        """Generate templates for all concepts in a chapter."""
        specs = self.get_concepts_for_chapter(chapter_key)
        
        if not specs:
            logger.warning(f"No concepts found for chapter: {chapter_key}")
            # Use hardcoded fallback for factors_multiples
            specs = self._get_fallback_specs(chapter_key)
        
        # Limit to max_templates
        specs = specs[:max_templates]
        
        logger.info(f"Generating {len(specs)} templates for {chapter_key}")
        
        if dry_run:
            logger.info("DRY RUN - would generate these templates:")
            for spec in specs:
                logger.info(f"  - {spec.concept_id} @ {spec.bloom_level} (diff={spec.difficulty})")
            return []
        
        # Generate templates concurrently (with rate limiting)
        templates = []
        batch_size = 5  # Concurrent requests
        
        for i in range(0, len(specs), batch_size):
            batch = specs[i:i + batch_size]
            batch_templates = await asyncio.gather(
                *[self.generate_template(spec) for spec in batch],
                return_exceptions=True
            )
            
            for template in batch_templates:
                if isinstance(template, Exception):
                    logger.error(f"Template generation failed: {template}")
                else:
                    templates.append(template)
            
            # Rate limiting delay
            if i + batch_size < len(specs):
                await asyncio.sleep(1)
        
        return templates
    
    def _get_fallback_specs(self, chapter_key: str) -> List[TemplateSpec]:
        """Fallback specs when config files are missing."""
        if chapter_key == "factors_multiples":
            concepts = [
                ("math.class5.factors_multiples.factors", "Finding Factors"),
                ("math.class5.factors_multiples.multiples", "Finding Multiples"),
                ("math.class5.factors_multiples.gcd", "Greatest Common Divisor"),
                ("math.class5.factors_multiples.lcm", "Least Common Multiple"),
                ("math.class5.factors_multiples.divisibility", "Divisibility Rules"),
                ("math.class5.factors_multiples.prime_composite", "Prime and Composite Numbers"),
                ("math.class5.factors_multiples.prime_factorization", "Prime Factorization"),
            ]
            
            specs = []
            for concept_id, concept_name in concepts:
                for bloom in ["UNDERSTAND", "APPLY"]:
                    for diff in [2, 3]:
                        specs.append(TemplateSpec(
                            concept_id=concept_id,
                            concept_name=concept_name,
                            bloom_level=bloom,
                            difficulty=diff,
                            misconceptions=["ARITHMETIC_ERROR", "INCOMPLETE_REASONING"],
                        ))
            return specs
        
        return []
    
    async def _call_llm(self, prompt: str) -> str:
        """Call LLM API."""
        if self.llm_provider == "openai":
            return await self._call_openai(prompt)
        elif self.llm_provider == "anthropic":
            return await self._call_anthropic(prompt)
        elif self.llm_provider == "mock":
            return self._mock_response(prompt)
        else:
            raise ValueError(f"Unknown LLM provider: {self.llm_provider}")
    
    async def _call_openai(self, prompt: str) -> str:
        """Call OpenAI API."""
        try:
            import openai
            
            client = openai.AsyncOpenAI(api_key=self.api_key)
            
            response = await client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": self.SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                temperature=0.7,
                max_tokens=2000,
                response_format={"type": "json_object"}
            )
            
            return response.choices[0].message.content
            
        except ImportError:
            logger.warning("openai package not installed, using mock response")
            return self._mock_response(prompt)
    
    async def _call_anthropic(self, prompt: str) -> str:
        """Call Anthropic API."""
        try:
            import anthropic
            
            client = anthropic.AsyncAnthropic(
                api_key=self.api_key or os.environ.get("ANTHROPIC_API_KEY")
            )
            
            response = await client.messages.create(
                model=self.model or "claude-3-sonnet-20240229",
                max_tokens=2000,
                system=self.SYSTEM_PROMPT,
                messages=[{"role": "user", "content": prompt}]
            )
            
            return response.content[0].text
            
        except ImportError:
            logger.warning("anthropic package not installed, using mock response")
            return self._mock_response(prompt)
    
    def _mock_response(self, prompt: str) -> str:
        """Mock response for testing without API."""
        import random
        
        # Extract concept from prompt
        concept_match = "factors" if "factors" in prompt.lower() else "multiples"
        
        mock_template = {
            "template_code": f"{concept_match}_mock_v1",
            "question_pattern": f"Find all {concept_match} of {{{{ target_number }}}}.",
            "variable_schema": {
                "type": "object",
                "properties": {
                    "target_number": {
                        "type": "integer",
                        "minimum": 10,
                        "maximum": 50,
                        "description": "Number to analyze"
                    }
                }
            },
            "answer_logic": f"sorted([i for i in range(1, variables['target_number'] + 1) if variables['target_number'] % i == 0])" if concept_match == "factors" else "[variables['target_number'] * i for i in range(1, 6)]",
            "option_patterns": [
                "{{ correct_answer }}",
                "{{ distractor_1 }}",
                "{{ distractor_2 }}",
                "{{ distractor_3 }}"
            ],
            "estimated_time": random.choice([45, 60, 90]),
            "misconceptions": [
                {
                    "option_index": 1,
                    "misconception_code": "INCOMPLETE_REASONING",
                    "why_wrong": "Missing some elements",
                    "teaching_point": "Check all possibilities systematically"
                }
            ],
            "rationale": "This template tests basic understanding with variable difficulty"
        }
        
        return json.dumps(mock_template)
    
    def _parse_llm_response(self, response: str) -> Dict[str, Any]:
        """Parse LLM JSON response."""
        try:
            # Try to find JSON in response
            response = response.strip()
            
            # Handle markdown code blocks
            if "```json" in response:
                start = response.find("```json") + 7
                end = response.find("```", start)
                response = response[start:end].strip()
            elif "```" in response:
                start = response.find("```") + 3
                end = response.find("```", start)
                response = response[start:end].strip()
            
            return json.loads(response)
            
        except json.JSONDecodeError as e:
            logger.error(f"Failed to parse LLM response: {e}")
            logger.error(f"Response was: {response[:500]}...")
            return {}
    
    def save_templates(
        self,
        templates: List[GeneratedTemplate],
        output_path: str = None
    ) -> str:
        """Save generated templates to JSON file."""
        if output_path is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = f"generated_templates_{timestamp}.json"
        
        data = [t.to_dict() for t in templates]
        
        with open(output_path, 'w') as f:
            json.dump(data, f, indent=2)
        
        logger.info(f"Saved {len(templates)} templates to {output_path}")
        return output_path


class TemplateIngestionService:
    """
    Service to ingest generated templates into the database.
    
    Handles: Validation → Deduplication → Insert → Queue for Review
    """
    
    def __init__(self, db_session):
        self.db = db_session
    
    def ingest_templates(
        self,
        templates: List[GeneratedTemplate],
        auto_publish: bool = False,
        created_by: str = "llm_generator"
    ) -> Dict[str, Any]:
        """Ingest templates into database."""
        from db.models.templates import QuestionTemplate, TemplateStatus
        
        results = {
            "ingested": 0,
            "duplicates": 0,
            "validation_failed": 0,
            "errors": []
        }
        
        for template in templates:
            try:
                # Check for duplicates
                existing = self.db.query(QuestionTemplate).filter(
                    QuestionTemplate.template_code == template.template_code
                ).first()
                
                if existing:
                    results["duplicates"] += 1
                    continue
                
                # Validate
                validation = self._validate_template(template)
                if not validation["passed"]:
                    results["validation_failed"] += 1
                    results["errors"].append(f"{template.template_code}: {validation['errors']}")
                    continue
                
                # Create DB record
                db_template = QuestionTemplate(
                    concept_id=template.concept_id,
                    template_code=template.template_code,
                    question_pattern=template.question_pattern,
                    variable_schema=template.variable_schema,
                    answer_logic=template.answer_logic,
                    option_patterns=template.option_patterns,
                    difficulty=template.difficulty,
                    bloom_level=template.bloom_level,
                    estimated_time=template.estimated_time,
                    status=TemplateStatus.REVIEW.value if not auto_publish else TemplateStatus.PUBLISHED.value,
                    validation_passed=True,
                    created_by=created_by
                )
                
                self.db.add(db_template)
                results["ingested"] += 1
                
            except Exception as e:
                results["errors"].append(f"{template.template_code}: {str(e)}")
        
        self.db.commit()
        return results
    
    def _validate_template(self, template: GeneratedTemplate) -> Dict[str, Any]:
        """Validate template before ingestion."""
        errors = []
        
        if not template.concept_id:
            errors.append("Missing concept_id")
        if not template.question_pattern:
            errors.append("Missing question_pattern")
        if not template.answer_logic:
            errors.append("Missing answer_logic")
        if len(template.option_patterns) < 2:
            errors.append("Need at least 2 options")
        
        # Validate answer logic syntax
        try:
            compile(template.answer_logic, '<answer_logic>', 'eval')
        except SyntaxError as e:
            errors.append(f"Invalid answer_logic: {e}")
        
        return {"passed": len(errors) == 0, "errors": errors}


async def main():
    """CLI entry point."""
    import argparse
    
    logging.basicConfig(level=logging.INFO)
    
    parser = argparse.ArgumentParser(description="Generate templates using LLM")
    parser.add_argument("--concept", type=str, help="Single concept to generate for")
    parser.add_argument("--chapter", type=str, default="factors_multiples", help="Chapter key")
    parser.add_argument("--count", type=int, default=5, help="Number of templates")
    parser.add_argument("--batch", action="store_true", help="Generate for all concepts in chapter")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be generated")
    parser.add_argument("--provider", type=str, default="mock", choices=["openai", "anthropic", "mock"])
    parser.add_argument("--model", type=str, help="LLM model to use")
    parser.add_argument("--output", type=str, help="Output file path")
    parser.add_argument("--ingest", action="store_true", help="Ingest into database")
    
    args = parser.parse_args()
    
    generator = LLMTemplateGenerator(
        llm_provider=args.provider,
        model=args.model
    )
    
    if args.batch or args.chapter:
        templates = await generator.generate_batch(
            chapter_key=args.chapter,
            max_templates=args.count,
            dry_run=args.dry_run
        )
        
        if templates:
            output_file = generator.save_templates(templates, args.output)
            print(f"✅ Generated {len(templates)} templates → {output_file}")
            
            if args.ingest:
                from core.database import SessionLocal
                with SessionLocal() as db:
                    ingestion = TemplateIngestionService(db)
                    result = ingestion.ingest_templates(templates)
                    print(f"📥 Ingested: {result['ingested']}, Duplicates: {result['duplicates']}")
    else:
        print("Use --batch or --chapter to generate templates")


if __name__ == "__main__":
    asyncio.run(main())
