"""add lean template schema

Revision ID: 9aa8a735074b
Revises: 4c5c17305393
Create Date: 2026-01-14 17:43:17.571745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa8a735074b'
down_revision: Union[str, None] = '4c5c17305393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_qbank_template_id', table_name='question_bank_items')
    op.create_index(op.f('ix_question_bank_items_template_id'), 'question_bank_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_bank_items_template_id'), table_name='question_bank_items')
    op.create_index('idx_qbank_template_id', 'question_bank_items', ['template_id'], unique=False)
    # ### end Alembic commands ###
