"""add lean template schema tables

Revision ID: a1b2c3d4e5f6
Revises: 4c5c17305393
Create Date: 2026-01-14 17:45:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '4c5c17305393'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create question_templates table if it doesn't exist
    connection = op.get_bind()
    if not connection.dialect.has_table(connection, 'question_templates'):
        op.create_table('question_templates',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('concept_id', sa.String(length=255), nullable=False),
            sa.Column('template_code', sa.Text(), nullable=False),
            sa.Column('question_pattern', sa.Text(), nullable=False),
            sa.Column('variable_schema', sa.JSON(), nullable=False),
            sa.Column('answer_logic', sa.Text(), nullable=False),
            sa.Column('option_patterns', sa.JSON(), nullable=False),
            sa.Column('difficulty', sa.Integer(), nullable=False),
            sa.Column('bloom_level', sa.String(length=50), nullable=False),
            sa.Column('estimated_time', sa.Integer(), nullable=False),
            sa.Column('status', sa.Enum('draft', 'review', 'approved', 'published', 'archived', name='templatestatus'), nullable=False),
            sa.Column('validation_passed', sa.Boolean(), nullable=False),
            sa.Column('validation_errors', sa.JSON()),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('created_by', sa.String(length=255)),
            sa.Column('reviewed_by', sa.String(length=255)),
            sa.Column('published_at', sa.DateTime(timezone=True)),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_question_templates_concept_id'), 'question_templates', ['concept_id'], unique=False)
        op.create_index(op.f('ix_question_templates_status'), 'question_templates', ['status'], unique=False)
    
    # Create misconceptions table if it doesn't exist
    if not connection.dialect.has_table(connection, 'misconceptions'):
        op.create_table('misconceptions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('code', sa.String(length=100), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('description', sa.Text(), nullable=False),
            sa.Column('teaching_point', sa.Text(), nullable=False),
            sa.Column('subject', sa.String(length=50), nullable=False),
            sa.Column('concept_tags', sa.JSON()),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('code')
        )
        op.create_index(op.f('ix_misconceptions_code'), 'misconceptions', ['code'], unique=False)
    
    # Create template_option_misconceptions table if it doesn't exist
    if not connection.dialect.has_table(connection, 'template_option_misconceptions'):
        op.create_table('template_option_misconceptions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('template_id', sa.Integer(), nullable=False),
            sa.Column('misconception_id', sa.Integer(), nullable=False),
            sa.Column('option_index', sa.Integer(), nullable=False),
            sa.Column('custom_explanation', sa.Text()),
            sa.ForeignKeyConstraint(['misconception_id'], ['misconceptions.id'], ),
            sa.ForeignKeyConstraint(['template_id'], ['question_templates.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    # Create template_diagrams table if it doesn't exist
    if not connection.dialect.has_table(connection, 'template_diagrams'):
        op.create_table('template_diagrams',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('template_id', sa.Integer(), nullable=False),
            sa.Column('diagram_type', sa.String(length=50), nullable=False),
            sa.Column('name', sa.String(length=255), nullable=False),
            sa.Column('render_pattern', sa.Text()),
            sa.Column('variables', sa.JSON()),
            sa.Column('cdn_url_base', sa.String(length=500)),
            sa.Column('file_path', sa.String(length=500)),
            sa.Column('width', sa.Integer()),
            sa.Column('height', sa.Integer()),
            sa.Column('alt_text', sa.Text()),
            sa.Column('caption', sa.Text()),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['template_id'], ['question_templates.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_diagrams')
    op.drop_table('template_option_misconceptions')
    op.drop_index(op.f('ix_misconceptions_code'), table_name='misconceptions')
    op.drop_table('misconceptions')
    op.drop_index(op.f('ix_question_templates_status'), table_name='question_templates')
    op.drop_index(op.f('ix_question_templates_concept_id'), table_name='question_templates')
    op.drop_table('question_templates')
    op.execute("DROP TYPE templatestatus")
    # ### end Alembic commands ###
