"""add_quality_fields_to_templates

Revision ID: edf6e4d85934
Revises: c8f1f14c81d0
Create Date: 2026-01-17 04:39:19.206062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf6e4d85934'
down_revision: Union[str, None] = 'c8f1f14c81d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add quality fields to question_templates for rich question content
    op.add_column('question_templates', 
        sa.Column('solution_pattern', sa.Text(), nullable=True, 
                  comment='Jinja2 template for step-by-step solution with variable placeholders'))
    op.add_column('question_templates', 
        sa.Column('solution_steps_schema', sa.JSON(), nullable=True, 
                  comment='Schema defining solution steps generation rules'))
    op.add_column('question_templates', 
        sa.Column('hint_pattern', sa.Text(), nullable=True, 
                  comment='Jinja2 template for progressive hints'))
    op.add_column('question_templates', 
        sa.Column('narrative_pattern', sa.Text(), nullable=True, 
                  comment='Jinja2 template for rich story narrative'))
    op.add_column('question_templates', 
        sa.Column('diagram_config', sa.JSON(), nullable=True, 
                  comment='Diagram type and variable mappings for CDN rendering'))
    
    # Index fixes
    op.drop_index('idx_qbank_template_id', table_name='question_bank_items')
    op.create_index(op.f('ix_question_bank_items_template_id'), 'question_bank_items', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove quality fields from question_templates
    op.drop_column('question_templates', 'diagram_config')
    op.drop_column('question_templates', 'narrative_pattern')
    op.drop_column('question_templates', 'hint_pattern')
    op.drop_column('question_templates', 'solution_steps_schema')
    op.drop_column('question_templates', 'solution_pattern')
    
    # Index fixes
    op.drop_index(op.f('ix_question_bank_items_template_id'), table_name='question_bank_items')
    op.create_index('idx_qbank_template_id', 'question_bank_items', ['template_id'], unique=False)
    # ### end Alembic commands ###
