"""
Pydantic models for rich question generation (Hybrid Neuro-Symbolic Architecture)
Separates mathematical skeleton from narrative skin
"""

from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
from enum import Enum


class DifficultyLevel(str, Enum):
    """Difficulty progression aligned with Bloom's taxonomy"""
    EASY = "easy"
    MEDIUM = "medium"
    HARD = "hard"
    EXPERT = "expert"


class BloomLevel(str, Enum):
    """Bloom's cognitive levels"""
    REMEMBER = "remember"
    UNDERSTAND = "understand"
    APPLY = "apply"
    ANALYZE = "analyze"
    EVALUATE = "evaluate"
    CREATE = "create"


class MathSkeleton(BaseModel):
    """Deterministic mathematical skeleton (generated by SymPy)"""
    
    concept: str = Field(..., description="Core mathematical concept (e.g., 'Finding Factors', 'LCM')")
    question_type: str = Field(..., description="Type of question (e.g., 'factor-identification', 'lcm-calculation')")
    difficulty: DifficultyLevel = Field(..., description="Difficulty level")
    bloom_level: BloomLevel = Field(..., description="Cognitive level required")
    
    # Parameters generated by reverse-engineering (guaranteed valid)
    parameters: Dict[str, Any] = Field(..., description="Math parameters (e.g., {'number': 24, 'factors': [1,2,3,4,6,8,12,24]})")
    
    # LaTeX representation of the math
    latex_problem: str = Field(..., description="LaTeX formatted problem statement")
    
    # Solution details
    solution: Any = Field(..., description="Correct answer (could be list, dict, or scalar)")
    steps: List[str] = Field(default=[], description="Step-by-step solution steps in LaTeX")
    explanation: str = Field(default="", description="Mathematical explanation")
    
    # Validation
    is_valid: bool = Field(default=True, description="Whether the skeleton passed validation")
    validation_notes: str = Field(default="", description="Notes from validation (e.g., 'All factors verified')")


class KCNagStoryContext(BaseModel):
    """K.C. Nag pedagogical context (generated by LLM with Instructor)
    
    Follows K.C. Nag philosophy:
    - Real-world relevance
    - Progressive building
    - Visual thinking
    - Story-driven learning
    """
    
    story_character: str = Field(..., description="Main character in the story (e.g., 'Akshara the baker')")
    story_setting: str = Field(..., description="Real-world context (e.g., 'A bakery in Mumbai')")
    story_action: str = Field(..., description="What the character is doing (e.g., 'arranging cookies in boxes')")
    real_world_relevance: str = Field(..., description="Why this matters (e.g., 'Knowing factors helps with packing')")
    visual_hint: str = Field(..., description="Description of visual aid (e.g., 'Grid showing 6 columns of cookies')")
    
    # How the numbers appear in the story
    number_placement: str = Field(..., description="Where the target number appears (e.g., 'Total cookies: {number}')")
    
    # Connection to concept
    concept_bridge: str = Field(..., description="How story connects to mathematical concept")
    
    # Follow-up question for deeper thinking
    extension_question: str = Field(..., description="Challenge question to extend learning")


class RichQuestion(BaseModel):
    """Complete rich question combining skeleton + skin"""
    
    id: str = Field(default="", description="Unique question ID")
    chapter_id: str = Field(..., description="Chapter identifier (e.g., 'ch5')")
    
    # The math
    skeleton: MathSkeleton = Field(..., description="Deterministic mathematical structure")
    
    # The story
    story: KCNagStoryContext = Field(..., description="K.C. Nag pedagogical context")
    
    # Rendered outputs
    html_problem: str = Field(default="", description="HTML rendered problem for frontend")
    latex_full: str = Field(default="", description="Complete LaTeX for PDF export")
    
    # Metadata
    generation_metadata: Dict[str, Any] = Field(default_factory=dict, description="Metadata about generation")
    
    # Quality validation
    round_trip_validated: bool = Field(default=False, description="Whether answer was verified against solver")
    validation_message: str = Field(default="", description="Any validation errors or notes")


class RichQuestionRequest(BaseModel):
    """Request to generate a rich question"""
    
    chapter_id: str = Field(..., description="Chapter ID (e.g., 'ch5')")
    concept: str = Field(..., description="Specific concept (e.g., 'factors')")
    difficulty: DifficultyLevel = Field(default=DifficultyLevel.EASY, description="Difficulty level")
    bloom_level: BloomLevel = Field(default=BloomLevel.REMEMBER, description="Target Bloom level")
    theme: Optional[str] = Field(default=None, description="Optional theme for story (e.g., 'cooking', 'sports')")


class RichQuestionResponse(BaseModel):
    """Response with rich question"""
    
    success: bool = Field(..., description="Whether generation succeeded")
    question: Optional[RichQuestion] = Field(default=None, description="Generated question")
    error: Optional[str] = Field(default=None, description="Error message if failed")
    generation_time_ms: float = Field(..., description="Time taken to generate (milliseconds)")
